select 'T4' as TEST_CASE_ID,'S4' as TEST_SCENARIO, 123 as RECORDS_COUNT,'EXP4' as EXPECTED_RESULT, 'RES4' as TEST_RESULT, current_timestamp() as RUN_TIME;

select 'T5' as TEST_CASE_ID,'S5' as TEST_SCENARIO, 123 as RECORDS_COUNT,'EXP5' as EXPECTED_RESULT, 'RES5' as TEST_RESULT, current_timestamp() as RUN_TIME;

select 'T6' as TEST_CASE_ID,'S6' as TEST_SCENARIO, 123 as RECORDS_COUNT,'EXP6' as EXPECTED_RESULT, 'RES6' as TEST_RESULT, current_timestamp() as RUN_TIME;